export enum ReactGraphTokens {
  PLAN_AND_SELECT_NODE = "REACT_GRAPH_PLAN_AND_SELECT_NODE",
  EXECUTE_TOOL_NODE = "REACT_GRAPH_EXECUTE_TOOL_NODE",
  REFLECT_AND_DECIDE_NODE = "REACT_GRAPH_REFLECT_AND_DECIDE_NODE",
  GENERATE_ANSWER_NODE = "REACT_GRAPH_GENERATE_ANSWER_NODE",
  CLARIFY_NODE = "REACT_GRAPH_CLARIFY_NODE",
}
